### ISSUE TITLE
File contains data in an unknown format

### ISSUE THREAD

**Issue by JokerHYC** [tsurumeso/vocal-remover#104]
I:\vocal-remover> python inference.py --input 3.mp3
loading model... done
loading wave source... C:\Users\hyc\AppData\Local\Programs\Python\Python38\lib\site-packages\librosa\core\audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
Traceback (most recent call last):
  File "C:\Users\hyc\AppData\Local\Programs\Python\Python38\lib\site-packages\librosa\core\audio.py", line 149, in load
    with sf.SoundFile(path) as sf_desc:
  File "C:\Users\hyc\AppData\Local\Programs\Python\Python38\lib\site-packages\soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\hyc\AppData\Local\Programs\Python\Python38\lib\site-packages\soundfile.py", line 1183, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "C:\Users\hyc\AppData\Local\Programs\Python\Python38\lib\site-packages\soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '3.mp3': File contains data in an unknown format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 172, in <module>
    main()
  File "inference.py", line 133, in main
    X, sr = librosa.load(
  File "C:\Users\hyc\AppData\Local\Programs\Python\Python38\lib\site-packages\librosa\core\audio.py", line 166, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Users\hyc\AppData\Local\Programs\Python\Python38\lib\site-packages\librosa\core\audio.py", line 190, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Users\hyc\AppData\Local\Programs\Python\Python38\lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError

**Comment by JokerHYC** [comment]
I didn't install ffmpeg....that's why it's not work.
