### ISSUE TITLE
ModuleNotFoundError: No module named 'torch._C'

### ISSUE THREAD

**Issue by SF12-Studies** [tsurumeso/vocal-remover#109]
I'm running _Python 3.7.4_ and I have installed torch using the ```requirements.txt```. 
I have tried running the AI using ```python train.py --dataset E:\Vocal Rem\train --reduction_rate 0.5 --mixup_rate 0.5 --gpu 0``` but it outputs:

```
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    import torch.nn as nn
  File "C:\Users\Chaiyo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "C:\Users\Chaiyo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\__init__.py", line 1, in <module>
    from .module import Module
  File "C:\Users\Chaiyo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 7, in <module>
    from ..parameter import Parameter
  File "C:\Users\Chaiyo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\parameter.py", line 2, in <module>
    from torch._C import _disabled_torch_function_impl
ModuleNotFoundError: No module named 'torch._C'
```

**Comment by tsurumeso** [comment]
Please refer to [GET STARTED](https://pytorch.org/get-started/locally/) and reinstall PyTorch.
