### ISSUE TITLE
RuntimeError: Numpy is not available - module compiled against API version 0x10 but version of numpy is 0xf

### ISSUE THREAD

**Issue by dviralfi** [tsurumeso/vocal-remover#110]
Trying to use inference.py, 4 months ago it worked, nut now it does'nt :|
Got this Error:

"loading model... c:\Users....\inference.py:131: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  device = torch.device('cpu')
done

loading wave source... done
stft of wave source... done
  0%|                                                             
                                                           
Traceback (most recent call last):
  File "c:\Users\....some_file.py", line 407, in <module>
    main(base_song_path,vocal_song_path)
    y_spec, v_spec = sp.separate(X_spec)
  File "c:\Users\...\inference.py", line 73, in separate
    mask = self._separate(X_mag_pad, roi_size)
  File "c:\Users\...\inference.py", line 38, in _separate
    X_batch = torch.from_numpy(X_batch).to(self.device)
RuntimeError: Numpy is not available

**Comment by dviralfi** [comment]
I found the problem!
The dependencies for `vocal-remover` are: 
numpy>=1.21,<1.22 (because of `numba 0.55.2` that requires it to be <1.22)
python>3.9, <3.10
