### ISSUE TITLE
colab issue

### ISSUE THREAD

**Issue by lunk3rs** [tsurumeso/vocal-remover#123]
keep getting this error.  Was working fine earlier:
Now processing: Butterfly 
with HP2-4BAND-3090_4band_arch-500m_1.pth
loading model... done
stft of wave source... Traceback (most recent call last):
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 307, in <module>
    main()
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 293, in main
    multi_file(useModel, args.input)
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 244, in multi_file
    process.inference()
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 94, in inference
    X_spec_m, input_high_end_h, input_high_end = spec_utils.loadWave(self.input, mp, hep=self.hep)
  File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/lib/spec_utils.py", line 14, in loadWave
    X_wave[bands_n+1], _ = librosa.load(
TypeError: load() takes 1 positional argument but 3 positional arguments (and 2 keyword-only arguments) were given
Notebook took: 23.7s

**Comment by vagrantvv** [comment]
> keep getting this error. Was working fine earlier: Now processing: Butterfly with HP2-4BAND-3090_4band_arch-500m_1.pth loading model... done stft of wave source... Traceback (most recent call last): File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 307, in main() File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 293, in main multi_file(useModel, args.input) File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 244, in multi_file process.inference() File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/main.py", line 94, in inference X_spec_m, input_high_end_h, input_high_end = spec_utils.loadWave(self.input, mp, hep=self.hep) File "/content/drive/MyDrive/VocalRemover5-COLAB_arch/lib/spec_utils.py", line 14, in loadWave X_wave[bands_n+1], _ = librosa.load( TypeError: load() takes 1 positional argument but 3 positional arguments (and 2 keyword-only arguments) were given Notebook took: 23.7s

got the same error

**Comment by vagrantvv** [comment]
got the same error

**Comment by vagrantvv** [comment]
here‘s the solution，it works on me：
> 
> > Put `!pip install librosa==0.9.1` in the audio separation cell of the UVR 5.2 Colab notebook
> 

https://github.com/NaJeongMo/Colaboratory-Notebook-for-Ultimate-Vocal-Remover/issues/3#issuecomment-1487809822
