### ISSUE TITLE
Baseline File Not found

### ISSUE THREAD

**Issue by vikassingh2023** [tsurumeso/vocal-remover#140]
getting this while using
 C:\Windows\System32\vocal-remover>python inference.py --input C:\Users\shadow\Downloads\12_ladke.mp3
loading model... Traceback (most recent call last):
  File "C:\Windows\System32\vocal-remover\inference.py", line 184, in <module>
    main()
  File "C:\Windows\System32\vocal-remover\inference.py", line 127, in main
    model.load_state_dict(torch.load(args.pretrained_model, map_location=device))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/baseline.pth'

**Comment by rogermiranda1000** [comment]
If you have cloned the master branch instead of downloading from the [release tab](https://github.com/tsurumeso/vocal-remover/releases/tag/v5.0.3) please download it from there.

**Comment by vikassingh2023** [comment]
Hello,
Thanks for answering but got new issue -
C:\ProgramData\Anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Traceback (most recent call last):
  File "C:\Users\arman\Downloads\vocal-remover\inference.py", line 4, in <module>
    import librosa
  File "C:\Users\arman\AppData\Roaming\Python\Python39\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "C:\Users\arman\AppData\Roaming\Python\Python39\site-packages\librosa\core\__init__.py", line 9, in <module>
    from .constantq import *  # pylint: disable=wildcard-import
  File "C:\Users\arman\AppData\Roaming\Python\Python39\site-packages\librosa\core\constantq.py", line 1059, in <module>
    dtype=np.complex,
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by rogermiranda1000** [comment]
Try with `numpy==1.24.4`, it's the one I'm using

**Comment by vicwomg** [comment]
I ran into both these issues, and it turns out that in addition to `numpy==1.24.4`, bumping to `librosa==0.10.1` was needed
