### ISSUE TITLE
Pre-release model RuntimeError: Error(s) in loading state_dict for CascadedNet

### ISSUE THREAD

**Issue by marcindulak** [tsurumeso/vocal-remover#201]
The baseline.pth file included in the release https://github.com/tsurumeso/vocal-remover/releases/tag/v6.0.0b4 fails with https://github.com/tsurumeso/vocal-remover/commit/99f92fe4b6bfe37bf4ff5bf4110ce224007312e5.
https://github.com/tsurumeso/vocal-remover/releases/tag/v5.1.1 seems to work.

# To reproduce

## Install

```
git clone https://github.com/tsurumeso/vocal-remover
cd vocal-remover
git checkout 99f92fe4b6bfe37bf4ff5bf4110ce224007312e5
cd -
```

```
docker run --detach --workdir /opt/vc --rm -v $PWD/vocal-remover:/opt/vc --name vc debian:stable bash -c "sleep infinity"

docker exec -it vc bash -c "apt-get update && apt-get install --yes git curl python-is-python3 python3-dev python3-pip python3-venv unzip"
docker exec -it vc bash -c "cd ~/ && python -m venv venv && . venv/bin/activate"
docker exec -it vc bash -c "echo 'if [ -f ~/venv/bin/activate ]; then . ~/venv/bin/activate; fi' >> ~/.bashrc"
docker exec -it vc bash -ci "python -m pip install -r requirements.txt"
```

Torch is also needed https://github.com/tsurumeso/vocal-remover/issues/171
```
docker exec -it vc bash -ci "python -m pip install torch==2.*"
```

```
# OSError: cannot load library 'libsndfile.so': libsndfile.so: cannot open shared object file: No such file or directory
# ImportError: libGL.so.1: cannot open shared object file: No such file or directory
# ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
docker exec -it vc bash -c "apt-get update && apt-get install --yes libsndfile1 libgl1 libglib2.0-0"
```

```
docker exec -it vc bash -ci "curl -sLo input.wav https://upload.wikimedia.org/wikipedia/commons/f/fd/Ryan_Merkley_20190817.wav"
```

## Run failed v6.0.0b4

```
docker exec -it vc bash -ci "curl -sLO https://github.com/tsurumeso/vocal-remover/releases/download/v6.0.0b4/vocal-remover-v6.0.0b4.zip"
docker exec -it vc bash -ci "unzip vocal-remover-v6.0.0b4.zip vocal-remover/models/baseline.pth"
docker exec -it vc bash -ci "rm -f models/baseline.pth && mv vocal-remover/models/baseline.pth models/baseline.pth"
docker exec -it vc bash -ci "python inference.py --input input.wav"
```

```
/opt/vc/inference.py:131: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(args.pretrained_model, map_location='cpu'))
loading model... Traceback (most recent call last): 
  File "/opt/vc/inference.py", line 189, in <module>
    main()
  File "/opt/vc/inference.py", line 131, in main
    model.load_state_dict(torch.load(args.pretrained_model, map_location='cpu'))
  File "/root/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2584, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for CascadedNet:
        Missing key(s) in state_dict: "aux_out.weight". 
        size mismatch for out.weight: copying a param with shape torch.Size([4, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 32, 1, 1]).
```

## Run successful v5.1.1

```
docker exec -it vc bash -ci "curl -sLO https://github.com/tsurumeso/vocal-remover/releases/download/v5.1.1/vocal-remover-v5.1.1.zip"
docker exec -it vc bash -ci "unzip vocal-remover-v5.1.1.zip vocal-remover/models/baseline.pth"
docker exec -it vc bash -ci "rm -f models/baseline.pth && mv vocal-remover/models/baseline.pth models/baseline.pth"
docker exec -it vc bash -ci "python inference.py --input input.wav"
```

**Comment by marcindulak** [comment]
The problem is due to not using the branch https://github.com/tsurumeso/vocal-remover/tree/v6 which corresponds to the baseline.pth file included in the release https://github.com/tsurumeso/vocal-remover/releases/tag/v6.0.0b4.

See https://github.com/tsurumeso/vocal-remover/issues/195
