### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 404000** [tsurumeso/vocal-remover#23]
Traceback (most recent call last):
  File "inference.py", line 11, in <module>
    from lib import dataset
  File "C:\Users\DESKTOP\Desktop\vocal-remover\lib\dataset.py", line 10, in <module>
    class VocalRemoverValidationSet(torch.utils.data.Dataset):
AttributeError: module 'torch.utils' has no attribute 'data'

**Comment by tsurumeso** [comment]
Please update your PyTorch version to 1.3.0 or above.

**Comment by 404000** [comment]
I have pytorch latest version 1.5.0
