### ISSUE TITLE
Missing models/baseline.pth

### ISSUE THREAD

**Issue by luissiqueira** [tsurumeso/vocal-remover#28]
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
loading model... Traceback (most recent call last):
  File "inference.py", line 104, in <module>
    main()
  File "inference.py", line 31, in main
    model.load_state_dict(torch.load(args.model, map_location=device))
  File "/media/luissiqueira/storage/workspace/roove/vocal-remover/venv/lib/python3.6/site-packages/torch/serialization.py", line 584, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/media/luissiqueira/storage/workspace/roove/vocal-remover/venv/lib/python3.6/site-packages/torch/serialization.py", line 234, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/media/luissiqueira/storage/workspace/roove/vocal-remover/venv/lib/python3.6/site-packages/torch/serialization.py", line 215, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/baseline.pth'

**Comment by Gebro13** [comment]
how to  solve this problem?

**Comment by thiezn** [comment]
The file models/baseline.pth isn't included in the github repository itself. You can either train your own model or instead of cloning the repo, download the release which does have the pretrained model included here: https://github.com/tsurumeso/vocal-remover/releases/tag/v5.0.2

**Comment by sumitshrestha** [comment]
> The file models/baseline.pth isn't included in the github repository itself. You can either train your own model or instead of cloning the repo, download the release which does have the pretrained model included here: https://github.com/tsurumeso/vocal-remover/releases/tag/v5.0.2

This release does not have the model.
