### ISSUE TITLE
Needs improvement

### ISSUE THREAD

**Issue by 404000** [tsurumeso/vocal-remover#40]
I tried a song, this vocal remover has removed a part of the singer's voice and left the rest did not remove it

**Comment by Anjok07** [comment]
Are you basing this concern off the model the AI comes with? If you want better results, train a model with a dataset that includes the type of music you want to remove vocals from.

**Comment by 404000** [comment]
when i train my own model he said that you need nvidea , graphic cart nvidea I do not own it , i have intel 
(base) C:\Users\DESKTOP\Downloads\vocal-remover-v3.0.0\vocal-remover>python train.py -i dataset/instruments -m dataset/mixtures -M 0.5 -g 0
1 05_too_mix.wav 05_too_inst.wav
Traceback (most recent call last):
  File "train.py", line 225, in <module>
    main()
  File "train.py", line 136, in main
    model.cuda()
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 458, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 354, in _apply
    module._apply(fn)
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 354, in _apply
    module._apply(fn)
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 354, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 376, in _apply
    param_applied = fn(param)
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 458, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\cuda\__init__.py", line 186, in _lazy_init
    _check_driver()
  File "C:\Users\DESKTOP\miniconda3\lib\site-packages\torch\cuda\__init__.py", line 68, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError:
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

**Comment by aufr33** [comment]
You have several options.
1) Run on CPU. It will be VERY slow and you will have to keep your PC on for several weeks.
2) Buy GTX 1070 or higher.
3) Rent a server with GPU.
4) Try Google Collab.

**Comment by 404000** [comment]
i want Run  on CPU give me the comand line

**Comment by aufr33** [comment]
@404000 
If you seriously want to run this on the CPU, then the command line in the README file. But if you run this on your home PC, then you will fail, because OS can sometimes hang, electricity may go out and you will have to start learning over and over again.

**Comment by 404000** [comment]
I did not find a command line in the README file , I found this only python train.py -i dataset/instruments -m dataset/mixtures -M 0.5 -g 0

**Comment by aufr33** [comment]
@404000
Just use https://github.com/Anjok07/ultimatevocalremovergui

**Comment by 404000** [comment]
https://github.com/Anjok07/ultimate vocal remover gui doesn't contain train module's button , if you want train module must-do it from the command line

**Comment by aufr33** [comment]
There is already a quality model there. I think the author will retrain it for version 3.0.0 soon.

**Comment by 404000** [comment]
but i said https://github.com/Anjok07/ultimatevocalremovergui doesn't contain train module's button , if you want train module must-do it from the command line and i want the command line on cpu
