### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by ThatGuythatlikesRubyLanguage** [tsurumeso/vocal-remover#86]
My goal was to extract all instruments from this video: https://www.youtube.com/watch?v=lsQAoDsH0Ws
I gathered similiar sounding audio from freesound.org mixed it into a 10 minute music (i designed it just for the ai its not supposed to be normal music) to train my model on. So not general model just for specific instruments. I got this error:
Traceback (most recent call last):
  File "train.py", line 224, in <module>
    main()
  File "train.py", line 200, in main
    batchsize=args.batchsize)
  File "train.py", line 48, in train_inner_epoch
    return sum_loss / len(X)
ZeroDivisionError: division by zero
Even if the ai wouldnt train the best on such a small dataset, is there a fix?

**Comment by tsurumeso** [comment]
The size of the dataset should be at least 5 pairs when using the default `--val_rate`.
