### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dataset/mixtures'

### ISSUE THREAD

**Issue by cherisetan93** [tsurumeso/vocal-remover#9]
Hello, great job there.
I ran this code and I had this error, did I miss out something in the project? 
python augment.py -i dataset/instrumentals -m dataset/mixtures -p 1

Traceback (most recent call last):
  File "augment.py", line 25, in <module>
    for fname in os.listdir(args.mixture_dataset)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dataset/mixtures'

**Comment by cherisetan93** [comment]
C:\Users\PycharmProjects\vocal-remover-master>python inference.py --input C:\Users\Downloads\GreenhouseGirl.wav
loading model... Traceback (most recent call last):
  File "inference.py", line 91, in <module>
    main()
  File "inference.py", line 30, in main
    model.load_state_dict(torch.load(args.model))
  File "C:\Python35-64\lib\site-packages\torch\serialization.py", line 419, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/baseline.pth'
