### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by Z2r-YT** [tsurumeso/vocal-remover#90]
tried using the solution one has already posted here, nothing fixed it. anyone help?

`python train.py --dataset C:\Users\blank\Desktop\vocal-remover-v4.0.0\Training --reduction_rate 5 --mixup_rate 5 --gpu 0
`
```
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
# epoch 0
  * inner epoch 0
Traceback (most recent call last):
  File "train.py", line 224, in <module>
    main()
  File "train.py", line 195, in main
    train_loss = train_inner_epoch(
  File "train.py", line 48, in train_inner_epoch
    return sum_loss / len(X)
ZeroDivisionError: division by zero
```

**Comment by tsurumeso** [comment]
Is the dataset correctly placed and are there at least a few tens of pairs?
In addition, `--reduction_rate` and `--mixup_rate` should be more than 0 and less than 1.
