### ISSUE TITLE
ValueError: cannot reshape array of size 0 into shape (9917,1025,2) (training)

### ISSUE THREAD

**Issue by ITAC85v2** [tsurumeso/vocal-remover#95]
This is an error I can't seem to solve during training on 4.0.0
Entire tracelog is:

_**Traceback (most recent call last):
  File "train.py", line 224, in <module>
    main()
  File "train.py", line 154, in main
    offset=model.offset)
  File "C:\Users\Deedl\Downloads\vocal-remover-v4.0.0\vocal-remover\lib\dataset.py", line 151, in make_validation_set
    X, y = spec_utils.cache_or_load(X_path, y_path, sr, hop_length, n_fft)
  File "C:\Users\Deedl\Downloads\vocal-remover-v4.0.0\vocal-remover\lib\spec_utils.py", line 151, in cache_or_load
    y = np.load(inst_cache_path)
  File "C:\Users\Deedl\AppData\Roaming\Python\Python37\site-packages\numpy\lib\npyio.py", line 440, in load
    pickle_kwargs=pickle_kwargs)
  File "C:\Users\Deedl\AppData\Roaming\Python\Python37\site-packages\numpy\lib\format.py", line 768, in read_array
    array.shape = shape[::-1]
ValueError: cannot reshape array of size 0 into shape (9917,1025,2)**_

I am running this on Python 3.7 on Windows 10 64bit, with torch 1.8.1+cpu and torchvision 0.9.1+cpu, if that helps any.

**Comment by tsurumeso** [comment]
I think it was caused by a broken cache.
Please try to remove the cache directories placed at the following:
```
path/to/dataset/
  +- instruments/
  |    +- sr{}_hl{}_nf{}  # this is the instrumental cache dir
  |    +- 01_foo_inst.wav
  |    +- 02_bar_inst.mp3
  |    +- ...
  +- mixtures/
       +- sr{}_hl{}_nf{}  # this is the mixture cache dir
       +- 01_foo_mix.wav
       +- 02_bar_mix.mp3
       +- ...
```

**Comment by ITAC85v2** [comment]
That wasn't the issue, I found out the issue on my own. You apparently need at least 10 samples to train from, and (I think) they must be multiples of 10.

**Comment by averwhy** [comment]
If youve resolved the problem, please close the issue :)

**Comment by ITAC85v2** [comment]
Sorry, I forgot about the issue. Thank you for reminding me!
