### ISSUE TITLE
Permission denied: 'models/baseline.pth'

### ISSUE THREAD

**Issue by Pasanlaksitha** [tsurumeso/vocal-remover#96]
**command**

python inference.py -i D:\Geo\vocal-remover\1.wav

**error**

loading model... Traceback (most recent call last):
  File "inference.py", line 166, in <module>
    main()
  File "inference.py", line 110, in main
    model.load_state_dict(torch.load(args.pretrained_model, map_location=device))
  File "C:\Users\$$$$\AppData\Roaming\Python\Python38\site-packages\torch\serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\$$$$\AppData\Roaming\Python\Python38\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\$$$$\AppData\Roaming\Python\Python38\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'models/baseline.pth'

**Comment by filispeen** [comment]
Run the console in that folder as administrator and run the command or transfer the folder with the program to another drive if the folder is in drive C:
